services:
  DEMETR:
    image: DEMETR:latest
    container_name: DEMETR
    build:
      context: .
      target: dev
    ports:
      - "443:4000"
    networks:
      - DEMETR_network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  DEMETR_network:
    driver: bridge
