services:
  N4tflix:
    image: N4tflix:latest
    container_name: N4tflix
    build:
      context: .
      target: dev
    ports:
      - "443:4000"
    networks:
      - N4tflix_network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  N4tflix_network:
    driver: bridge
