services:
  watchmen:
    image: watchmen:latest
    container_name: watchmen
    build:
      context: .
      target: dev
    ports:
      - "443:4000"
    networks:
      - watchmen_network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  watchmen_network:
    driver: bridge
